          spring:
            application:
              name: CONFIG-DEV-NAME
          eureka:
            client:
              service-url:
                defaultZone: http://localhost:8761/eureka/
